local vec = Vector3(0, 1, 2)
print(vec:Normalize())
print(vec:Length())
print(vec:LengthSqr())
print(vec:Length2D())
print(vec:Length2DSqr())
print(vec:Dot(Vector3(0, 1, 2)))
print(vec:Cross(Vector3(0, 1, 2)))
print(vec:Clear())
print(vec:Right())
print(vec:Up())
print(vec:Angles())
print(vec:Vectors())
